version: '3.8'

services:
  data_provider_service:
    container_name: data-provider-service
    build:
      context: ./data_provider_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  dashboard_service:
    container_name: dashboard-service
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - data_provider_service
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    container_name: celery-instance
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    command: celery -A dashboard_service worker --loglevel=info
    depends_on:
      - redis
      - dashboard_service
      - data_provider_service
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - C_FORCE_ROOT=true
