# Generated by Django 5.1.2 on 2024-10-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardevent',
            name='hotel_id',
            field=models.CharField(max_length=36),
        ),
    ]
