# Generated by Django 5.1.2 on 2024-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardEvent',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('room_id', models.CharField(max_length=36)),
                ('night_of_stay', models.DateField()),
                ('rpg_status', models.IntegerField(choices=[(1, 'Booking'), (2, 'Cancellation')])),
                ('timestamp', models.DateTimeField()),
                ('hotel_id', models.CharField(max_length=36)),
            ],
        ),
    ]
